application: kjlthefirm
version: 1
runtime: python
api_version: 1

handlers:
- url: /s
  static_dir: s

- url: /admin/(.*)
  script: admin.py
  login: admin

- url: /tests
  static_dir: tests

- url: /.*
  script: controllers/main.py
  login: required